"""
Simple TFJS model.json reader
"""

import json
import sys


def read_model_json(json_path):
    """Read and display TFJS model.json file contents"""
    with open(json_path, 'r') as f:
        model_data = json.load(f)

    print("=" * 60)
    print("TFJS Model Information")
    print("=" * 60)

    print(f"\nFormat: {model_data.get('format')}")
    print(f"Generated by: {model_data.get('generatedBy')}")
    print(f"Converted by: {model_data.get('convertedBy')}")

    print("\n" + "=" * 60)
    print("Weight Manifests")
    print("=" * 60)

    for i, manifest in enumerate(model_data.get('weightsManifest', [])):
        print(f"\nManifest {i + 1}:")
        print(f"  Paths: {manifest.get('paths')}")
        print(f"  Number of weights: {len(manifest.get('weights', []))}")

        print("\n  Weights:")
        for weight in manifest.get('weights', []):
            print(f"    • {weight['name']}")
            print(f"      Shape: {weight['shape']}")
            print(f"      Dtype: {weight['dtype']}")

    return model_data


if __name__ == "__main__":
    if len(sys.argv) > 1:
        # Read from command line argument
        model_data = read_model_json(sys.argv[1])
    else:
        # Default path
        print("Usage: python read_model.py <path_to_model.json>")
        print("\nOr edit the script and uncomment the line below with your path:")
        print("# model_data = read_model_json('path/to/your/model.json')")
